def problem2(range):
    '''Each new term in the Fibonacci sequence is generated by adding the
    previous two terms. By starting with 1 and 2, the first 10 terms will
    be:
    
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    
    By considering the terms in the Fibonacci sequence whose values do
    not exceed four million, find the sum of the even-valued terms.'''
    
    a,b,sum = 1,2,0
    while a < range:
        if a%2==0:
            sum += a
        a,b = b, a+b
    return sum

if __name__ == "__main__":
    import sys
    print problem2(int(sys.argv[1]))
